php:
  preset: laravel
  disabled:
    - no_unused_imports
  finder:
    not-name:
      - index.php
js:
  finder:
    not-name:
      - webpack.mix.js
      - mix.js("resources/js/app.js", "public/js")
    .postCss("resources/css/app.css", "public/css", [
      require("tailwindcss"),
  ]);
css: true

